---
title: "PH241 HW8"
author: "Kunal Mishra"
date: "3/14/2018"
output:
  pdf_document: default
  html_document: default
---

### Question 1A
```{r}
# Setting up Multilevel data
multilevelAlcoholConsumption = array(
    c(29, 75, 51, 45, 
      386, 280, 87, 22),
    dim=c(4,2),
    dimnames=list( c("Alcohol Consumption - 0-39g/day", "40-79", "80-119", ">120"),
                   c("Esophegeal Cancer - Case", "Control")
    )
)
multilevelAlcoholConsumption

chisq.test(multilevelAlcoholConsumption,
           correct=FALSE)
```

### Question 1D  
```{r, message=FALSE}
library(ggplot2)
library(data.table)

caseProportions = as.data.table(multilevelAlcoholConsumption)
colnames(caseProportions)[1] = "Case"
caseProportions[, CaseProportion := Case/(Case+Control)]
caseProportions

ggplot(data=caseProportions[, .(CaseProportion)][, Stratum:=1:4],
       aes(x=Stratum, y=CaseProportion, group=1)) + 
    geom_line()
```

### Question 1F
```{r, message=FALSE}
logCaseProportions = caseProportions[, .(CaseProportion=log(CaseProportion/(1-CaseProportion)))][, Stratum:=1:4]

head(logCaseProportions)

ggplot(data=logCaseProportions,
       aes(x=Stratum, y=CaseProportion, group=1)) +
    geom_line()
```

